//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunMoon.Blog.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.Keywords = new HashSet<Keyword>();
        }
    
        public System.Guid ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Author { get; set; }
        public Nullable<System.Guid> TopicID { get; set; }
        public string IP { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
    }
}
