//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunMoon.Blog.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> TopicId { get; set; }
        public Nullable<System.Guid> CommendId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
