//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunMoon.Blog.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Comments = new HashSet<Comment>();
            this.Keywords = new HashSet<Keyword>();
        }
    
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Author { get; set; }
        public string CatagoryID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> CommentCount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
        public virtual User User { get; set; }
    }
}
